"""
"" 21st FEB 2026 ::: Irfan Habeeb Gazi
"" 12th FEB 2026 ::: Surjayan Kar
"" 10th DEC 2025 ::: Vivek Halder
""
"" Usage: sage Decrypt.py <priv_key> <pub_key> <ciphertext>
""
"" This program decrypts a given ciphertext (stored as a pair of points) using Elliptic Curve Cryptography.
"" The private and public key files must generated by the user and stored in the corresponding files.
"" Please refer to KeyGeneration.py for more details.
"" The ciphertext is expected to encrypted by the sender using Encrypt.py. Please refer to the program for more details.
"" The decyprted message is printed to the console.
""
"" The arguments to be provided to the program are as follows:
"" 1. <mode>: 1 = ASCII message decryption, 2 = point decryption
"" 2. <priv_key> : The path to file containing the private key.
"" 3. <public_key> : The path to file containing the public key for the cryptosystem. This file also
"" stores the elliptic curve parameters to be used.
"" 4. <ciphertext> : The ciphertext to be decrypted. This file must be generated by the sender
"" using Encrypt.py on a valid message. It may contain a single ciphertext (mode 0 and 1)
"" or multiple ciphertexts (mode 1 and 2).
""
"" <Sample Input / Output>
""
"" INPUT 1:
"" Mode: 2
"" ecc_public_key.txt:-
"" {
"" public_key": "(7 : 13*a + 1 : 1)",
"" generator": "(8 : 16*a + 7 : 1)",
"" coefficients": "(2, 3, 5, 7, 11)",
"" field_order": "289",
"" field_degree": "2"
"" }
""
"" ecc_private_key.txt:-
"" {
"" private_key": "6"
"" }
""
"" ecc_ciphertext.txt:-
"" {
"" "C1": "(2 : 16*a + 13 : 1)",
"" "ciphertexts": [
""    {
""      "C2": "(4*a + 3 : 3*a + 5 : 1)"
""    },
""    {
""      "C2": "(13*a + 7 : 11*a + 7 : 1)"
""    }
""  ]
"" }
""
"" OUTPUT 1:
"" Decrypted Message Points M:
"" (12 : 2 : 1)
"" (12 : 3 : 1)
""
"" Time Taken - 0.678s (Linux x86_64 - ASUS TUF 2022)
""
"" INPUT 2:
"" Mode: 1
"" ecc_private_key.txt:-
"" {
""   "private_key": "1290693952626734646789"
"" }
""
"" ecc_public_key.txt:-
"" {
""   "public_key": "(95896570400982669048054269309280068466 : 101613368519350077389271444278575641331 : 1)",
""   "generator": "(146509865186709558332568654250747812154 : 296706650525226469128366357359881794645 : 1)",
""   "coefficients": "(135679116661939155249036766490267172875, 278115415174837476836815625805522646686, 139871793268352908519147087491400262288, 135428774238550599914948378814411507415, 126880101249320461602323281701382698900)",
""   "base_field": "297654049293069287429956324068660269161",
""   "field_degree": "1"
"" }
""
"" ecc_ciphertext.txt:-
"" {
""   "C1": "(216514573003997318311497111277772753660 : 73659320715204783319201010854676518712 : 1)",
""   "ciphertexts": [
""     {
""       "C2": "(49140572008884922999946791252718317594 : 7997958877056945121114662135973535768 : 1)"
""     },
""     {
""       "C2": "(292334955947858292434208415312587747889 : 226145182840682224298779835679327659623 : 1)"
""     },
""     {
""       "C2": "(266397785150911654492759910607042933801 : 111119366618106463927154463924667927374 : 1)"
""     }
""   ]
"" }
""
"" OUTPUT 2:
"" Decrypted ASCII Message: the big brown fox jumped over the lazy dog 
""
"" Time Taken - 0.728s (Linux x86_64 - ASUS TUF 2022)
"""

import sys
import json
from sage.all import *

USAGE1 = "sage Decrypt.py 1 <priv_key> <pub_key> <ciphertext>"
USAGE2 = "sage Decrypt.py 2 <priv_key> <pub_key> <ciphertext>"
if (len(sys.argv) != 5):
    print("Invalid Arguments!")
    print(f"\nASCII Decryption: {USAGE1}")
    print("OR")
    print(f"Point Decryption: {USAGE2}")
    exit(1)


def load_json(filename):
    with open(filename, 'r') as file:
        data = json.load(file)
    return data


def parse_field(base_field, field_degree):
    if field_degree == 1:
        return GF(base_field)
    else:
        return GF((base_field, field_degree), names=('a',))


def parse_coeffs(coeffs_str, K):
    return [K(c.strip()) for c in coeffs_str]


def parse_point(point_str, E):
    point_str = point_str.strip()
    point_str = point_str[1:-1]
    coords = [s.strip() for s in point_str.split(':')]

    if len(coords) != 3:
        raise ValueError("Invalid point format: " + point_str)

    try:
        x = E.base_field()(coords[0])
        y = E.base_field()(coords[1])
        z = E.base_field()(coords[2])
    except Exception as ex:
        raise ValueError(
            f"Invalid coordinate in point: {point_str}. Error: {ex}")

    try:
        point = E(x, y, z)
    except Exception as ex:
        raise ValueError(
            f"Failed to construct point on curve: {point_str}. Error: {ex}"
        )

    return point


def parse_private_key(priv_key_str):
    return Integer(priv_key_str.strip())


def parse_ciphertext(ciphertext, E):
    C1_str, C2_str = ciphertext['C1'], ciphertext['C2']
    C1 = parse_point(C1_str, E)
    C2 = parse_point(C2_str, E)
    return C1, C2


def map_point_to_chars(P):
    if P.is_zero():
        return ""

    X = Integer(P[0])
    msg_chars = ""

    X = X >> 8  # Remove padding byte

    while X > 0:
        char_code = X & 0xFF
        msg_chars = msg_chars + chr(char_code)
        X = X >> 8

    return msg_chars


def main():
    mode = int(sys.argv[1])
    priv = load_json(sys.argv[2])
    pub = load_json(sys.argv[3])
    ciphertext = load_json(sys.argv[4])

    base_field = int(pub['base_field'].strip())
    field_degree = int(pub['field_degree'].strip())
    coeffs_str = pub['coefficients']
    coeffs_str = coeffs_str[1:-1].split(',')
    generator_str = pub['generator']
    public_key_str = pub['public_key']

    K = parse_field(base_field, field_degree)
    coeffs = parse_coeffs(coeffs_str, K)
    E = EllipticCurve(K, coeffs)
    G = parse_point(generator_str, E)
    public_key = parse_point(public_key_str, E)
    private_key = parse_private_key(priv['private_key'])

    if mode == 1:
        C1 = parse_point(ciphertext['C1'], E)
        if 'ciphertexts' in ciphertext:
            msg = ""
            for ct in ciphertext['ciphertexts']:
                C2 = parse_point(ct['C2'], E)
                M = C2 - private_key * C1
                chunk = map_point_to_chars(M)
                print("Decrypted Chunk: " + chunk)
                msg += chunk
            print("Decrypted ASCII Message: " + msg)
    elif mode == 2:
        points = []
        if not ('ciphertexts' in ciphertext):
            raise ValueError(
                "Mode 2: No valid ciphertexts found in the ciphertext file."
            )
        C1 = parse_point(ciphertext['C1'], E)
        for ct in ciphertext['ciphertexts']:
            C2 = parse_point(ct['C2'], E)
            M = C2 - private_key * C1
            points.append(M)
        print("Decrypted Message Points M: ")
        for pt in points:
            print(str(pt))
    else:
        raise ValueError("Invalid mode! Please choose a valid mode (1 or 2).")


if __name__ == "__main__":
    main()
